port: 5000
host: "0.0.0.0"
secrets_file: "/tmp/secrets.txt"
config:
  name: "MyApp"
  version: "1.0.0"
  description: "This is a sample configuration file."
monitoring:
  enabled: true
  notification_url: "http://192.168.32.10:8080/videos/device"
  max_video_length_seconds: 30
  buffered_video_in_seconds: 10
  output_dir: "/tmp"
  fps: 30
capture:
  device: 0
  width: 640
  height: 480
  fps: 30
  fourcc: "mp4v"
  output: "output.mp4"
  codec: "XVID"
  format: "mp4"
  save_frames: true
  save_video: true
  save_audio: false
